### ISSUE TITLE
I encountered some problems, need help

### ISSUE THREAD

**Issue by Mr-dbo** [mirceageorgescu/raspi-tank-2#1]
hi,brother

[git clone **\* raspi-tank-2]

[npm install async express pi-gpio socket.io]

I Run  [sudo node app.js]  , get the following error，Why is that?

pi@raspberrypi ~/raspi-tank-2 $ sudo node app.js 
Express server listening on port 3000
Error when trying to open pin 16
/bin/sh: 1: gpio-admin: not found

Error when trying to open pin 15
/bin/sh: 1: gpio-admin: not found

Error when trying to open pin 12
/bin/sh: 1: gpio-admin: not found

Error when trying to open pin 11
/bin/sh: 1: gpio-admin: not found

fs.js:77
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
            ^
Error: ENOENT, open '/sys/devices/virtual/gpio/gpio17/value'
    at Error (native)

**Comment by mirceageorgescu** [comment]
You also need to install gpio-admin:

```
git clone git://github.com/quick2wire/quick2wire-gpio-admin.git
cd quick2wire-gpio-admin
make
sudo make install
sudo adduser $USER gpio
```

After this, you will need to logout and log back in.

**Comment by Mr-dbo** [comment]
@mirceageorgescu 
Thank you for your reply.

I executed the command,install gpio-admin and  logout and log back in,get the following error，Why is that?

# 

pi@raspberrypi ~/raspi-tank-2 $ node app.js 
Express server listening on port 3000
Error when trying to open pin 16
gpio-admin: failed to change group ownership of /sys/devices/virtual/gpio/gpio23/direction: No such file or directory

Error when trying to open pin 15
gpio-admin: failed to change group ownership of /sys/devices/virtual/gpio/gpio22/direction: No such file or directory

Error when trying to open pin 12
gpio-admin: failed to change group ownership of /sys/devices/virtual/gpio/gpio18/direction: No such file or directory

Error when trying to open pin 11
gpio-admin: failed to change group ownership of /sys/devices/virtual/gpio/gpio17/direction: No such file or directory

fs.js:77
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
            ^
Error: ENOENT, open '/sys/devices/virtual/gpio/gpio17/value'
    at Error (native)

**Comment by mirceageorgescu** [comment]
see if this helps

http://raspberrypi.stackexchange.com/questions/27953/how-to-change-gpio-directory-for-node-js-pi-gpio

**Comment by Snipercaine** [comment]
I was getting the same error: failed to change ownership.  I tried changing the path as per the link above. Now I'm getting: 

"gpio-admin: could not flush data to /sys/class/gpio/export: Device or resource busy"

Any tips on fixing that?

I'm using a raspi 3

**Comment by nickschaos81** [comment]
I know this is old , but im hoping I could get some help. I am getting this error:
```
Express server listening on port 3000
/home/pi/rover/node_modules/async/dist/async.js:228
    return supportsSymbol && fn[Symbol.toStringTag] === 'AsyncFunction';

```
follow by:
```
 TypeError: Cannot read property 'undefined' of undefined
    at isAsync (/home/pi/rover/node_modules/async/dist/async.js:228:32)
    at wrapAsync (/home/pi/rover/node_modules/async/dist/async.js:232:12)
    at /home/pi/rover/node_modules/async/dist/async.js:3866:9
    at eachOfArrayLike (/home/pi/rover/node_modules/async/dist/async.js:1055:9)
    at eachOf (/home/pi/rover/node_modules/async/dist/async.js:1103:5)
    at _parallel (/home/pi/rover/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (/home/pi/rover/node_modules/async/dist/async.js:3948:5)
    at Object.tank.moveForward (/home/pi/rover/app.js:46:11)
    at Socket.<anonymous> (/home/pi/rover/app.js:87:14)
    at emitOne (events.js:77:13)
```
cloned your git for the tank 2. I would really like to get this working, thanks for your hard work on the code.

**Comment by mirceageorgescu** [comment]
@nickschaos81 yeah, this is really old and not maintained anymore.

I think async.js might have changed the syntax in the meantime.

You could update package.json to use the old version `"async": "0.9.0"`, instead of `"async": "^0.9.0"` or head to async.js documentation to figure out what changed.

Good luck!
.

**Comment by nickschaos81** [comment]
Actually I got it working. I removed the async all together. I say I got it working, I mean it's not giving me any errors. I still have to wire it up and will hopefully do that tonight.

Thank you for such a quick response. Would you mind if I fork your code? I am trying to learn javascript and node.js. Want to completely rework the code completely but it's nice to have a place to start.

**Comment by sebastianbila** [comment]
**gpio-admin: could not flush data to /sys/class/gpio/export: Device or resource busy**

What should i do?

**Comment by sebastianbila** [comment]
@Snipercaine Do you already fix your problem? I have the same and i need a help!!
