### ISSUE TITLE
app.js not running , throwing error

### ISSUE THREAD

**Issue by g1naveen** [mirceageorgescu/raspi-tank-2#2]
pi@raspberrypi ~/tank $ sudo node app.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/tank/app.js:4:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Any help how to resolve this issue?

**Comment by mirceageorgescu** [comment]
Looks like you don't have `async` installed. Did you run `npm install` before running the app?
